query account ($domain: String!) {
  account(where: {
    domain: $domain
  } ) {
    name
    domain
    eventbriteToken
    googleToken
    intercomToken
    sendgridToken
    stripeToken
    logo {
      url
    }
    users {
      email
    }
    dashboards {
      title
      blocks
      primaryColor
      backgroundColor
    }
  }
}
